<div class="mx-auto max-w-7xl space-y-6 p-6">
    <div><h1 class="text-2xl font-semibold text-slate-900">Payroll System Management</h1><p class="mt-1 text-sm text-slate-600">Control data authority and payroll-local canonical inputs.</p></div>
    @if(session('status'))<div class="rounded-md border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{{ session('status') }}</div>@endif
    <div class="grid gap-6 lg:grid-cols-2">
        @role('super-admin')
        <section class="rounded-lg border bg-white p-5"><h2 class="font-semibold">Operating mode</h2><p class="mt-2 text-sm">Active: <strong>{{ strtoupper($currentMode->value) }}</strong>@if($forced) · locked by environment @endif</p><div class="mt-3 flex gap-3">@foreach($allowedModes as $mode)<label><input type="radio" wire:model="selectedMode" value="{{ $mode->value }}" @disabled($forced)> {{ ucfirst($mode->value) }}</label>@endforeach</div>@error('mode')<p class="mt-2 rounded-md bg-red-50 p-2 text-xs text-red-700">{{ $message }}</p>@enderror @error('selectedMode')<p class="mt-2 rounded-md bg-red-50 p-2 text-xs text-red-700">{{ $message }}</p>@enderror @if($currentMode->value==='standalone' && $selectedMode==='connected')<button wire:click="previewReconciliation" class="mt-3 rounded-md border px-3 py-2 text-sm">Preview reconnect conflicts</button>@endif @if($reconciliation)<div class="mt-3 rounded-md bg-amber-50 p-3 text-xs">Local/source employees: {{ $reconciliation['local_employee_count'] }}/{{ $reconciliation['source_employee_count'] }} · Local only: {{ count($reconciliation['only_local']) }} · Source only: {{ count($reconciliation['only_source']) }} · Salary rates: {{ $reconciliation['local_salary_rates'] }}/{{ $reconciliation['source_salary_rates'] }}</div>@endif<input type="password" autocomplete="current-password" class="mt-3 w-full rounded-md border px-3 py-2 text-sm" wire:model="adminPassword" placeholder="Super administrator password" @disabled($forced)>@error('adminPassword')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror<button class="mt-3 rounded-md bg-slate-900 px-4 py-2 text-sm text-white disabled:opacity-50" wire:click="switchMode" @disabled($forced)>Change mode</button></section>
        @endrole
        <section class="rounded-lg border bg-white p-5"><h2 class="font-semibold">Payroll input readiness</h2><p class="mt-2 text-sm {{ $readiness['ready']?'text-emerald-700':'text-amber-700' }}">{{ $readiness['ready']?'Required payroll inputs are available':'Payroll inputs are incomplete' }}</p><ul class="mt-2 list-disc pl-5 text-sm">@foreach($readiness['errors'] as $error)<li>{{ $error }}</li>@endforeach</ul><dl class="mt-3 grid grid-cols-3 gap-2 text-sm">@foreach($readiness['counts'] as $label=>$count)<div><dt class="text-slate-500">{{ str($label)->headline() }}</dt><dd class="font-semibold">{{ $count }}</dd></div>@endforeach</dl><p class="mt-3 text-xs text-slate-500">This does not prevent entering Standalone mode. Missing inputs are checked during payroll generation.</p><p class="mt-1 text-xs text-slate-500">HRIS: {{ is_null($connections['hris'])?'not checked':($connections['hris']?'reachable':'offline') }} · Scheduler: {{ is_null($connections['payroll_scheduler'])?'not checked':($connections['payroll_scheduler']?'reachable':'offline') }}</p></section>
    </div>
    @role('super-admin')<section class="rounded-lg border bg-white p-5"><h2 class="font-semibold">Local account recovery</h2><p class="text-sm text-slate-600">Set a local password without contacting HRIS.</p><div class="mt-3 grid gap-3 md:grid-cols-[1fr_1fr_auto]"><input wire:model="accountEmpId" class="rounded-md border px-3 py-2 text-sm" placeholder="Employee ID"><input wire:model="accountPassword" type="password" class="rounded-md border px-3 py-2 text-sm" placeholder="New password (12+ characters)"><button wire:click="resetLocalPassword" class="rounded-md bg-slate-900 px-4 py-2 text-sm text-white">Reset password</button></div></section>@endrole
    <section class="rounded-lg border bg-white p-5"><div class="flex items-center justify-between"><div><h2 class="font-semibold">Canonical data import</h2><p class="text-sm text-slate-600">Consolidated and single-sheet workbooks use the same versioned schema.</p></div><div class="flex gap-2"><select wire:model="templateSheet" class="rounded-md border px-2 text-sm"><option value="">Consolidated template</option>@foreach(\App\Services\Payroll\CanonicalWorkbookService::SHEETS as $sheet)<option value="{{ $sheet }}">{{ $sheet }} only</option>@endforeach</select><button wire:click="downloadTemplate" class="rounded-md border px-3 py-2 text-sm">Download template</button></div></div><div class="mt-4 grid gap-3 md:grid-cols-[1fr_10rem_auto_auto]"><input type="file" wire:model="file" accept=".xlsx,.xlsm,.xls" class="rounded-md border p-2 text-sm"><input wire:model="period" placeholder="YYYY-MM" class="rounded-md border px-3 py-2 text-sm"><button wire:click="stage" class="rounded-md bg-indigo-600 px-4 py-2 text-sm text-white">Stage & validate</button>@if($selectedBatch && $selectedBatch->status==='validated')<button wire:click="activate" class="rounded-md bg-emerald-600 px-4 py-2 text-sm text-white">Activate #{{ $selectedBatch->id }}</button>@endif</div>@error('file')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror @if($selectedBatch && $selectedBatch->errors)<ul class="mt-3 list-disc pl-5 text-sm text-red-700">@foreach($selectedBatch->errors as $error)<li>{{ $error }}</li>@endforeach</ul>@endif</section>
    <section class="rounded-lg border bg-white p-5"><div class="flex justify-between"><h2 class="font-semibold">Source history</h2>@can('payroll.system.sync')@if($currentMode->value==='connected')<button wire:click="sync" class="rounded-md border px-3 py-2 text-sm">Synchronize connected sources</button>@endif @endcan</div><div class="mt-4 overflow-x-auto"><table class="w-full text-left text-sm"><thead><tr class="border-b"><th class="p-2">Batch</th><th>Source</th><th>Status</th><th>File</th><th>Activated</th><th></th></tr></thead><tbody>@foreach($batches as $batch)<tr class="border-b"><td class="p-2">#{{ $batch->id }}</td><td>{{ $batch->source }}</td><td>{{ $batch->status }}</td><td>{{ $batch->original_filename ?: '—' }}</td><td>{{ $batch->activated_at?->format('M d, Y H:i') ?: '—' }}</td><td>@can('payroll.system.rollback')@if($batch->status==='active')<button wire:click="rollback({{ $batch->id }})" wire:confirm="Rollback this active batch?" class="text-red-700">Rollback</button>@endif @endcan</td></tr>@endforeach</tbody></table></div></section>
</div>
