<div class="space-y-5 p-5 sm:p-6">
    <div class="flex flex-wrap items-start justify-between gap-3">
        <div><p class="text-xs font-semibold uppercase tracking-wide text-indigo-600">Payroll history</p><h1 class="mt-1 text-2xl font-semibold text-slate-900 dark:text-white">Past payroll imports</h1><p class="mt-1 text-sm text-slate-600 dark:text-slate-400">Resume staged workbooks or review imports already finalized into Payroll History.</p></div>
        <a href="{{ route('payroll.history.import') }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white shadow-sm">Import past payroll</a>
    </div>

    <section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900">
        <div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 p-4 dark:border-slate-700">
            <label class="relative block min-w-72 flex-1 sm:max-w-md"><span class="sr-only">Search imports</span><input type="search" wire:model.live.debounce.300ms="search" placeholder="Search workbook, period, or payroll type" class="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-950"></label>
            <div class="flex rounded-lg border border-slate-200 p-1 dark:border-slate-700">@foreach(['all' => 'All', 'staged' => 'Staged', 'finalized' => 'Finalized'] as $value => $label)<button type="button" wire:click="$set('statusFilter', '{{ $value }}')" class="rounded-md px-3 py-1.5 text-xs font-bold {{ $statusFilter === $value ? 'bg-indigo-600 text-white' : 'text-slate-600 dark:text-slate-300' }}">{{ $label }}</button>@endforeach</div>
        </div>
        <div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-100 text-xs font-bold uppercase tracking-wide text-slate-700 dark:bg-slate-800 dark:text-slate-200"><tr><th class="whitespace-nowrap px-4 py-2 text-left">Workbook</th><th class="whitespace-nowrap px-4 py-2 text-left">Period / type</th><th class="whitespace-nowrap px-4 py-2 text-right">Sheets</th><th class="whitespace-nowrap px-4 py-2 text-right">Rows</th><th class="whitespace-nowrap px-4 py-2 text-right">Matched</th><th class="whitespace-nowrap px-4 py-2 text-left">Status</th><th class="whitespace-nowrap px-4 py-2 text-left">Last activity</th><th class="px-4 py-2"></th></tr></thead>
            <tbody class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($imports as $historyImport)<tr><td class="max-w-sm px-4 py-3"><div class="truncate font-semibold text-slate-900 dark:text-white" title="{{ $historyImport->original_filename }}">{{ $historyImport->original_filename }}</div><div class="text-xs text-slate-500">Import #{{ $historyImport->id }}</div></td><td class="whitespace-nowrap px-4 py-3"><div class="font-medium">{{ \Carbon\CarbonImmutable::createFromFormat('!Y-m', $historyImport->payroll_period)->format('F Y') }}</div><div class="text-xs capitalize text-slate-500">{{ $historyImport->payroll_type_code }}</div></td><td class="px-4 py-3 text-right">{{ $historyImport->sheet_count }}</td><td class="px-4 py-3 text-right">{{ number_format($historyImport->row_count) }}</td><td class="px-4 py-3 text-right">{{ number_format($historyImport->matched_count) }}</td><td class="px-4 py-3"><span class="whitespace-nowrap rounded-full px-2 py-1 text-xs font-bold {{ $historyImport->status === 'applied' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-800' }}">{{ $historyImport->status === 'applied' ? 'Finalized' : 'Staged' }}</span></td><td class="whitespace-nowrap px-4 py-3 text-xs text-slate-500">{{ ($historyImport->applied_at ?? $historyImport->updated_at)->format('M d, Y g:i A') }}</td><td class="px-4 py-3 text-right"><a href="{{ route('payroll.history.import', ['import_id' => $historyImport->id]) }}" class="historical-import-history-action inline-flex whitespace-nowrap rounded-lg border px-3 py-1.5 text-xs font-bold">{{ $historyImport->status === 'applied' ? 'View' : 'Resume' }}</a></td></tr>@empty<tr><td colspan="8" class="px-4 py-10 text-center text-slate-500">No matching past payroll imports found.</td></tr>@endforelse</tbody>
        </table></div>
        @if($imports->hasPages())<div class="border-t border-slate-200 px-4 py-3 dark:border-slate-700">{{ $imports->links() }}</div>@endif
    </section>
</div>
