<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>MMMHMC.FingerprintHelper</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="DPUruNet">
      <HintPath>C:\Program Files\DigitalPersona\U.are.U RTE\Windows\Lib\.NET\DPUruNet.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>
</Project>
